export const GET_PAPER= "GET_PAPER"
export const POST_PAPER = "ADD_PAPER"

export const DELETE_PAPER = "DELETE_PAPER" 
export const PUT_PAPER = "UPDATE_PAPER" 



export const GET_PAPER_DETAILS_RESET ="GET_PAPER_DETAILS_RESET"

export const GET_PAPER_DETAILS_FAIL="GET_PAPER_DETAILS_FAIL"

export const GET_PAPER_DETAILS_REQUEST="GET_PAPER_DETAILS_REQUEST"
export const GET_PAPER_DETAILS_SUCCESS="GET_PAPER_DETAILS_SUCCESS"