export const GET_PRODUCT= "GET_PRODUCT"
export const POST_PRODUCT = "ADD_PRODUCT"

export const DELETE_PRODUCT = "DELETE_PRODUCT" 
export const PUT_PRODUCT = "UPDATE_PRODUCT" 



export const GET_PRODUCT_DETAILS_RESET ="GET_PRODUCT_DETAILS_RESET"

export const GET_PRODUCT_DETAILS_FAIL="GET_PRODUCT_DETAILS_FAIL"

export const GET_PRODUCT_DETAILS_REQUEST="GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS="GET_PRODUCT_DETAILS_SUCCESS"